### PR TITLE
Rest hook and functions

### PR DESCRIPTION
**Pull request by FakelsHub**
```
HOOK_TIMERREST (hs_timerrest.int) 
- Runs whenever the player uses the resting option in pip-boy.
- int     arg1 - the game time in ticks in the rest cycle. Compare with the current game time to get elapsed time in the rest cycle.
- int     arg2 - set to 1, at the end or the beginning(under certain conditions of time) of the rest cycle.
- int     ret1 - pass value 1, to immediately interrupt the rest.
```
`set_rest_mode` - Sets the mode for rest.
Mode flags:
set bit 1 - For all maps disable the use of rest from pip-boy. (DISABLE_REST)
set bit 2 - Will also disable the possibility of rest (for those maps, has already disable rest in Maps.txt) when absence of critters on the map. (DISABLE_REST_FIX)
set bit 3 - Disables self-healing during rest. (DISABLE_REST_HEAL)
value 0 - Restore rest of game default.

`set_rest_heal_time` - sets the time in minutes necessary for self-healing during rest.

### CODE REVIEW

**Comment by NovaRain** [comment]
I'd name the hook script RESTTIMER. And what's the "under certain conditions of time" that arg2 will be 1 at the beginning of the rest cycle?

**Comment by FakelsHub** [comment]
> I'd name the hook script RESTTIMER.

Оk. I will rename.

> what's the "under certain conditions of time"

The scripter will figure out what it is)
There is a complex rest loop algorithm, it will be set to 1 depending on the chosen rest time, in assembler not understand this.
Entered it as an additional argument. Perhaps this argument will be useful somewhere.

**Comment by NovaRain** [comment]
>The scripter will figure out what it is)
There is a hard rest loop algorithm, argument will be set to 1 depending on the chosen rest time, in assembler not understand this.
Entered it as an additional argument. Perhaps this argument will be useful somewhere.

The current "certain condition" is a bit too vague to make arg2 useful IMO. It'd be simpler and more consistent to set arg2 to 1 only when the rest timer stop (0x499DF2?) or interrupted by the player (pressing ESC during the rest).

**Comment by FakelsHub** [comment]
0x499DF2

**Comment by FakelsHub** [comment]
>  set arg2 to 1 only when the rest timer stops (0x499DF2?)

По этому адресу функция будет срабатывать только для опций от 1  hours

**Comment by FakelsHub** [comment]
ok, I'll come up with logic to suppress the begining triger. and add additional arg3. good night :-)

**Comment by NovaRain** [comment]
>ok, I'll come up with logic to suppress the begining triger. and add additional arg3.

I'm fine with an arg3 (rest interrupted by the player), but I still think it should be condensed to arg2; its value of 1 was supposed to mean a rest stops, no?

BTW, looks like the logic in the game engine to split the rest cycle to two parts when your time is not at XX:00. For example, if at 08:01 I choose to rest until 12:00, arg2 will be set to 1 after 59 mins passed and at the end, pretty much like "rest to 09:00 (less than an hour)" + "rest from 09:00 to 12:00 (three hours)". This should explain why arg2 is 1 near the beginning of a rest in some cases.

Or maybe just leave addrHook == 0x499DF2, so arg2 is only 1 if player rests more than one hour, making the whole thing simpler I guess.

**Comment by FakelsHub** [comment]
Fixed set to 1 of argument 2 at the beginning of rest cycle, plus added an interrupt the ESC key with value -1 to argument 2.
And added two arguments 'Hours' and 'Minutes' - this is the length of the rest cycle in hours and minutes, if I'm not mistaken.

**Pull request merged**
