### PR TITLE
Small fix for DD7

### PR DESCRIPTION
**Pull request by egornovivan**
https://github.com/sfall-team/sfall/issues/504#issuecomment-1949484919

### CODE REVIEW

**Comment by NovaRain** [comment]
I think I'll just change `int gMode = sf::IniReader::GetInt("Main", "GRAPHICS_MODE", 2, f2ResIni);` to 0/1 so sfall will use DD7 when HiResMode=1 and `f2_res.ini` not found.
The rest of mode checking changes are not needed IMO because when the code in Graphics.cpp is called (outside of `Graphics::init()`), `Graphics::mode` is already in range of 4-6, no point in checking 2/3. The same goes to DirectDraw.cpp as Graphics::mode is in range of 1-3.

**Comment by egornovivan** [comment]
Ok, close the pull request. What about `ddraw.dll = LoadLibraryA("wrapper\\ddraw.dll");`, should we wait or will you not add it?

**Comment by NovaRain** [comment]
Later I'll push the wrapper loading to a new branch for testing.

**Comment by egornovivan** [comment]
> I think I'll just change `int gMode = sf::IniReader::GetInt("Main", "GRAPHICS_MODE", 2, f2ResIni);` to 0/1 so sfall will use DD7 when HiResMode=1 and `f2_res.ini` not found.

There's a problem with `+ windowed;`

**Comment by NovaRain** [comment]
> > I think I'll just change `int gMode = sf::IniReader::GetInt("Main", "GRAPHICS_MODE", 2, f2ResIni);` to 0/1 so sfall will use DD7 when HiResMode=1 and `f2_res.ini` not found.
> 
> There's a problem with `+ windowed;`

`int windowed = (sf::IniReader::GetInt("Main", "WINDOWED", 0, f2ResIni) != 0) ? 1 : 0;`
`windowed` is 0 if `f2_res.ini` is not found. What's wrong with it?

**Comment by egornovivan** [comment]
> What's wrong with it?

Well, it is desirable that the window modes work

**Comment by NovaRain** [comment]
> > What's wrong with it?
> 
> Well, it is desirable that the window modes work

Why? TBH I don't understand the idea behind the whole "a preset if no `f2_res.ini`". Mash's HRP files are bundled in all modern digital releases and UPU/RPU and some other major TCs, minus _certain_ reporks, What's the use case when there's no `f2_res.ini` other than someone installs the base game from old CD?

**Comment by egornovivan** [comment]
> Why?

I use the CD(US) version because it is the least censored. In issue, the CNC developer also used this version for tests https://github.com/sfall-team/sfall/issues/504#issuecomment-1949363254

**Pull request closed without merging**
