### PR TITLE
INI Config reader

### LINKED ISSUE #468: Don't use GetPrivateProfile* WinAPI functions for loading INI
This is rather big issue considering how much INI option sfall itself loads, not to mention mods (especially EcCo, has a lot of ini settings, and will have even more...).

For every call to read a parameter (from sfall or script):

- It searches Windows Registry
- IF it can't find anything (and it won't ofc), then it loads and parses the entire ini file
- Then, returns a requested value

So instead we need an Ini Parser that:

- On first request, parses the ini file and saves sections & key/value pairs in dictionaries
- Saves the parsed INI memory afterwards
- If INI was requested from a script, it should unload it from memory on game reload (because we reset everything at that point, this is how we iterate on mods now).
- For sfall settings, it can keep them loaded at all times (we don't expect changes to INI to take effect without game restart)
- It should support loading ini from VFS (dat files), need to think about some kind of path prefix, or another solution so that root-based and mods-folder-based paths still work.

One option is to use built-in Fallout Config parser  (config_init, config_load, config_get_value, etc). Need to figure out how to get a list of sections and list of keys in section from that. config_load has parameter that allows to choose to load INI from "db" or from disk directly, which should cover the last requirement.

Another option is to write our own parser (or "adopt" some else's).

### PR DESCRIPTION
**Pull request by phobos2077**
- Replaced GetPrivateProfile* functions for reading ini with vanilla-based INI reader.
- Changed IniReader classes to read INI files once using new Config class and cache results until GameReset (going to main menu).
- Added metarule to read entire INI file in one operation and return as two-dimensional map array.
- Increased limits for INI strings to 1021.

Closes #468
Relates to #478

### CODE REVIEW

**Comment by phobos2077** [comment]
Measured time to initialize sfall using std::chrono high_resolution_clock.

Current develop branch: ~90ms.
Config parser branch: ~10ms.

**Comment by phobos2077** [comment]
There is a potential issue with caching. If sfall or script changes any INI value, subsequent reads will return the old value until game is reloaded. Probably need to address this inside IniReader.

**Review by NovaRain — APPROVED** [review]

**Comment by NovaRain** [comment]
Noticed a few things after comparing how `get_ini_*` functions work between pre-4.4 and 4.4. With a test ini like this:
```ini
[Test]
Key1=123
key2=456

; test duplicate sections and keys
[Section]
ThisOne=1
thisone=11
Setting1=100
settING1=101

[sectION]
ThisTwo=2
thistwo=22
SETTING2=200
setting2=202
```
and a script code to loop through the arrays:
```pas
sect := get_ini_sections("mods\\testfile.ini");
display_msg("Array len: " + len_array(sect));
foreach (sec in sect) begin
   display_msg("Test section: " + sec);
end

arr := get_ini_section("mods\\testfile.ini", "seCTion");
display_msg("Array len: " + len_array(arr));
foreach (key : val in arr) begin
   display_msg("Test key: " + key + ", val: " + val);
end
```
The results:
```
// 4.3.8
Array len: 3
Test section: Test
Test section: Section
Test section: sectION
Array len: 4
Test key: ThisOne, val: 1
Test key: thisone, val: 11
Test key: Setting1, val: 100
Test key: settING1, val: 101

// 4.4
Array len: 2
Test section: Section
Test section: Test
Array len: 4
Test key: Setting1, val: 100
Test key: SETTING2, val: 200
Test key: ThisOne, val: 1
Test key: ThisTwo, val: 2
```
1. The new ini reader in 4.4 uses `std::map`, so all entries are automatically sorted instead of keeping their order in the ini. Should it switch to `std::unordered_map` with case-insensitive hasher and comparer for retaining the order (and possible better performance)?
2. https://en.wikipedia.org/wiki/INI_file#Duplicate_names
   > The second occurrence of a property name may cause an abort, it may be ignored (and the value discarded), or it may override the first occurrence (with the first value discarded).

   Currently sfall ignores the second occurrence (due to how `std::map` handles existing key/value pairs), do you think it should be able to override the first value?

**Comment by phobos2077** [comment]
Is there a good reason supporting these edge cases? ini reader was implemented to match how Fallout reads configs. We can probably try to make ini functions more backwards compatible with pre 4.4, but I don't see how this will be useful.

**Comment by NovaRain** [comment]
> Is there a good reason supporting these edge cases? ini reader was implemented to match how Fallout reads configs. We can probably try to make ini functions more backwards compatible with pre 4.4, but I don't see how this will be useful.

For `std::map` and `std::unordered_map`, I suppose people would expect key/value pairs were in the same order as they are read by the reader. For whether the duplicate keys should override the value, I'm fine with current behavior as it's how `get_ini_setting` works in older sfall (returns the value from the first occurrence, not the second).

**Pull request merged**
