### PR TITLE
Disabling external wrapper for modes DX9

### PR DESCRIPTION
**Pull request by egornovivan**
https://github.com/sfall-team/sfall/issues/504

### CODE REVIEW

**Comment by NovaRain** [comment]
IniReader and built-in HRP modules are initialized _after_ `LoadOriginalDll()`.
IMO people who want to use an external wrapper should take care of those settings themselves.

**Comment by egornovivan** [comment]
Tell me how to do FileExist for f2_res.ini in your project and I may find a solution to all problems

**Comment by egornovivan** [comment]
I could have compiled the build locally, but it looks like my provider's DPI has gone crazy
изображение

**Comment by egornovivan** [comment]
@NovaRain I collected all the changes into two commits, compiled them, and tested them.

**Pull request closed without merging**
