### PR TITLE
Quickly moving items in inventory.

### PR DESCRIPTION
**Pull request by FakelsHub**
При перемещении предметов опция устанавливает максимальное количество предметов в окне ввода для перемещения. Так же позволяет пропустить диалоговое окно ввода при зажатой клавише.

The option sets the maximum number of items in the input window to move items. This also allows you to skip the input dialog when the key is hold down.

### CODE REVIEW

**Comment by NovaRain** [comment]
It should be put in [Input] section like other *Key options and disabled by default (0).

**Comment by FakelsHub** [comment]
> disabled by default (0)

in ddraw.ini just write ... = 0
This will prevent you from writing extra lines of options if you use ddraw.ini from Crafty.

**Comment by NovaRain** [comment]
>This will prevent from writing extra lines of options if use ddraw.ini from Crafty.

People should merge different settings in ddraw.ini by themselves when they want to use different sfall build.

**Comment by FakelsHub** [comment]
I understand the option to disable the  by default, which may somehow affect the game,  this does not affect the game, only improves the interaction of the interface with the user.

**Comment by NovaRain** [comment]
If the option was only holding down the key to skip the "Move Items" window, I'd say sure we can enable it by default. Because as long as player don't hold down the key, nothing will change. But for now it's not the case because just enabling the key alters the default behavior of the counter (set to max number rather than starting at 1).

**Comment by NovaRain** [comment]
>I do not see the point in separate options.

And I do not see the point forcing people to have the counter being set to max by default (the so-called _improvement_), when they might get used to the original behavior of item counter but still want the item fast move key. Also the BlockCall(0x4768A3) is not necessary for do_move_timer_hook to work.

>This must be 1 or the current maximum number of items, otherwise there will be an error.
What I mean is simply making a toggle option:
```
if (GetConfigInt("Misc", "ItemCounterDefaultMax", 0)) {
	BlockCall(0x4768A3); // mov  ebx, 1
}
```

**Comment by FakelsHub** [comment]
Want to quickly move 1 item?)

**Comment by NovaRain** [comment]
>Want to quickly move 1 item? (w/o dialog box)

No. I'm not sure why my posts above make you think I want something that's even more meaningless.
I've separated the code to two options for my own testing once I realized BlockCall(0x4768A3) isn't necessary.

- ItemFastMoveKey=29 & ItemCounterDefaultMax=0 - Holding down L-Ctrl to move the whole stack of items; without holding down the key the 'Move Items' counter starts at the original number of 1.

- ItemFastMoveKey=29 & ItemCounterDefaultMax=1 - Holding down L-Ctrl to move the whole stack of items; without holding down the key the 'Move Items' counter starts at max number. This is what your commit would do.

**Pull request merged**
